### ISSUE TITLE
The YouTube video doesn't cover the solution to question 2-d.

### ISSUE THREAD

**Issue by BowenLiu92** [brandon-rhodes/pycon-sql-tutorial#3]
Hi Mr. Rhodes,

Thank you so much for this amazing talk. Your SQL tutorial and Pandas tutorial are marvelous. I really appreciate what you've done.

But probably due to the video editing, the YouTube video doesn't actually cover the solution to question 2-d :"Which movie(s), not counting movies whose titles start with punctuation, come first in alphabetical order, and which come last?"

I tried "select * from movie where title REGEXP '[a-z]' order by title asc limit 10" with no luck. Could you illuminate how to solve the problem please?

Thanks.

**Comment by brandon-rhodes** [comment]
If you will check out the source code here on GitHub, you should final all the answers already in the comments — which I used as my reference while teaching:

https://github.com/brandon-rhodes/pycon-sql-tutorial/blob/master/exercises.rst

Enjoy!

**Comment by BowenLiu92** [comment]
Oh my. It worked. So sorry that I just saw this. Somehow Github didn't give me any notifications for your response. And as a total newbie in programming, I didn't know you can see the comments by clicking "Raw".

I just want to say I really appreciated all your effort and your talks on SQL and Pandas. I learned a lot and I found both of them to be engaging and entertaining. The Pandas audience didn't do justice to some great jokes. There's only one thing in SQL talk that I didn't get was when you talk about how SQL can process the requests like Python dictionaries. I don't know what would be the keys and what would be the values. Is it like `actor_id` will be the keys and `actor_name` will be values? But other than that, I understood everything. I love your talks better than MOOC.

Thanks again!

**Comment by brandon-rhodes** [comment]
Thank you, I am glad you found the talks helpful and that they helped you learn more!

If I was talking about SQL using temporary "hash tables" (what Python calls dictionaries) for merges, it could be any key and value depending on the SQL code. So while `movie join role on (movie.id = role.movie_id)` would have as one possible approach a scan of the `movie` table to map `movie.id` (key) to the movie’s whole data row (value), the query `movie join role on (movie.title = role.movie_title)` would instead want to build a temporary hash table where the keys were titles. That might have been what I had in mind.

**Comment by BowenLiu92** [comment]
Gotcha. Thanks a lot. I will definitely check out other talks from you on Python, and that's probably where I need your advice a bit:

As I'm a Python beginner (ultra-beginner compared to you), I'm sure some of your talks are above my level of understanding. Right now I am still learning about `class` on Python and can barely grind through easy DS & algo problems. Which talks of yours do you think would be helpful for someone at my level? The one I'm planning to watch is the "Dictionary Even Mightier". BTW, the number of talks you did was astounding. Thank you for contributing so much to the open source society!

BTW, I definitely need to check out the movie Sleuth. You used it in both of your talks. It must be worth watching, good or bad.

**Comment by brandon-rhodes** [comment]
I do not have a list of my talks sorted by skill level, so I am not sure which would be best to start with, though "The Mighty Dictionary" from 2010 might be one to try. Several of my PyOhio talks also, if I recall, also aimed at a novice audience. Maybe I should someday, if I get time, try to make a list of the talks sorted roughly by skill level.
